project:
  type: website

format:
  html:
    theme: yeti
    css: styles.css
    toc: false
    link-external-newwindow: true

website:
  title: "Roslyn Dakin"
  navbar:
    left:
      - href: index.html
        text: Home
      - href: team.html
        text: Team
      - href: research.html
        text: Research
      - href: papers.html
        text: Papers
      - href: teaching.html
        text: Teaching
      - href: media.html
        text: Media

editor: visual



